-- Config file generated by blmake!
-- `hooks` and `project_metadata` expect specific key-value pairs as values. Leave empty if unused.
-- All other tables expect string values. Leave empty if unused.
-- `debugging` expects a boolean value.
-- Everything else expects a string value. Use "" if unused.

Full_build = {
    compiler = "",        -- The compiler to be used (e.g., "gcc", "clang")
    lang_exts = {},       -- Language standard and extensions (e.g., "-std=c11", "-fno-exceptions")
    src_dir = "",         -- Source directory
    files = {},           -- A list of source files to compile (e.g., "main.cpp", "utils.cpp")
    include_dirs = {},    -- Directories for include files 
    preproc_opts = {},    -- Preprocessor options (e.g., macros, include paths)
    linker_opts = {},     -- Linker options (e.g., libraries, library paths)
    dependencies = {},    -- Libraries to link against, e.g. "m" for the math lib.
    out_dir = "",         -- Output directory
    output = "",          -- Output file name (optional, defaults to a.out)
    optimization = "",    -- Optimization level (e.g., "-O2", "-Os")
    debugging = true,     -- Will add "-g" if true.
    warnings = {},        -- Warning levels and options (e.g., "all", "error")
    platform_opts = {},   -- Platform-specific options (e.g., architecture flags)
    profiling = "",       -- Profiling options (e.g., "-pg")
    lto = "",             -- Link-time optimization (e.g., "-flto")
    post_build = {},      -- e.g., {"run_tests", "deploy"}
    build_type = "",      -- "Debug" or "Release"
    env_vars = {},        -- e.g., {CC = "gcc", CXX = "g++"}
    hooks = {},           -- e.g., {pre_build = "scripts/pre_build.sh", post_build = "scripts/post_build.sh"} 
    custom_flags = {},    -- e.g., {"-fno-stack-protector"}
    tests = {},           -- e.g., {"test_suite1", "test_suite2"}
    documentation = "",   -- Directory or command for generating docs
    project_metadata = {} -- Optional: name = "", author = "", version = ""
}

-- Customize behavior below!
-- For example:
--[[
if Full_build.build_type == "Debug" then
    Full_build.optimization = "-O0"
end
]]
