-- Config file generated by blmake!
-- All tables expect string values. Leave empty if unused.
-- `debugging` expects a boolean value.
-- Everything else expects a string value. Use "" if unused.

Build = {
    compiler = "g++",     -- e.g., "g++"
    files = {"main.cpp"},        -- e.g., {"main.cpp", "utils.cpp"}
    lang_exts = {},    -- e.g., {"-std=c++20"}
    include_dirs = {}, -- Directories for include files (optional)
    dependencies = {}, -- Preprocessor options (e.g., macros, include paths)
    preproc_opts = {}, -- Preprocessor options (e.g., macros, include paths)
    linker_opts = {},  -- Linker options (e.g., "m" for the math lib)
    optimization = "", -- Optimization level (e.g., "-O2", "-Os")
    debugging = true,  -- A BOOLEAN value indicating whether to include debugging info ("-g")
    build_type = "",   -- e.g., "Debug" or "Release"
    output = "",       -- e.g., "myprogram"
    src_dir = "",      -- Source directory
    out_dir = "",      -- Output directory
}

-- Customize behavior below!
-- For example:
--[[
if Full_build.build_type == "Debug" then
    Full_build.optimization = "-O0"
end
]]
